### ISSUE TITLE
R686 encoding/VHV

### ISSUE THREAD

**Issue by epoudrier** [polyrhythm-project/rds-scores#126]
There are some issues with staff attribution and drum set part on VHV. Can we verify that the encoding is correct?
![Screen Shot 2020-12-16 at 4 27 03 PM](https://user-images.githubusercontent.com/15526880/102422401-91a6e400-3fbb-11eb-91ca-56082b938545.png)
Here is the Suter score:
![Screen Shot 2020-12-16 at 4 29 05 PM](https://user-images.githubusercontent.com/15526880/102422541-dfbbe780-3fbb-11eb-97cd-fb384d262cb0.png)

**Comment by epoudrier** [comment]
@craigsapp Add L.H. text to first measure of piano part and add the cross staff notes for the full example.

**Comment by epoudrier** [comment]
System bug affecting piano and drum set.

**Comment by craigsapp** [comment]
L.H. Text and cross staff notes added in this commit:

https://github.com/polyrhythm-project/rds-scores/commit/c943d1058b1e41667a44c41e532fe52cc2ec57f1#diff-49cbb3d71ea54bbf2016be9c813fd40e519e46fab7802556f272bb77fe7c72cc

Piano/drum instrument labeling are in the Humdrum-to-MEI converter reported as issue https://github.com/humdrum-tools/verovio-humdrum-viewer/issues/468

**Comment by craigsapp** [comment]
Early conversions of MusicXML to Humdrum added the letter "x" to indicate that the note was unpitched.  This also has a meaning that the note is invisible.  The final encoding for unpitched notes adds the letter "R" instead of "x", so replacing the letters causes the notes to become visible.  Notes using "R" are assumed to be in treble clef (technically percussion clef, which adopts the treble clef names).  This part is in bass clef, so the pitches also needed to be adjusted to be as if the were on the treble clef.  (this probably needs to be added to the  MusicXML-to-Humdum converter).
