### ISSUE TITLE
copy/paste vs easy download into vhv

### ISSUE THREAD

**Issue by cdf75ubc** [polyrhythm-project/rds-scores#84]
The result you get from copying/pasting from GitHub to VHV using the option "raw + control A + control C/V" is different than the suggested "easy download into VHV" (page 12 of Editing RDS Humdrum files).
I tested all Bartók files: R350, for example, is pink when copying/pasting, but it is fine (although different) when browsing "polyrhythm project rds".

**Comment by craigsapp** [comment]
I will have to see you do it, since there could be various possibilities for the cause of the problem.   I had a similar problem recently (maybe it was during my presentation last week), where the file had not finished loading in the raw view, so copy of the text was incomplete.  After waiting for the entire file to display in the raw view, the copy worked.
